Repository CA-G12/Quiz-app-Team5, pull requests merged in 2022-07, with the labels that each got.

#2 create the file structure
  index.html
  script.js
  style/style.css
Labels: for-review

#6 Add text color
  style/style.css
Labels: approved

#7 creat a home page with h1 and disciption and button
  index.html
  style/style.css
Labels: for-review

#9 4 creat home page
  index.html
  style/style.css
Labels: for-review

#10 Test
  index.html
Labels: for-review

#11 game page
  game.html
  style/style.css
Labels: for-review

#17 i added the questions
  script.js
Labels: done

#18 start event
  index.html
Labels: to-do

#20 12 start event
  game.html
  script.js
  style/style.css
Labels: for-review

#19 create the random function
  game.html
  script.js
  style/style.css
Labels: for-review

#21 Next button functionality
  game.html
  script.js
  style/style.css
Labels: for-review
